from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "song_requests.db"


def load_local_env() -> None:
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return

    for line in env_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("'\""))


load_local_env()

_db_initialized = False


def get_database_url() -> str | None:
    return os.getenv("DATABASE_URL")


def is_postgres() -> bool:
    return bool(get_database_url())


def placeholder() -> str:
    return "%s" if is_postgres() else "?"


def placeholders(count: int) -> str:
    return ", ".join(placeholder() for _ in range(count))


def get_connection() -> Any:
    db_url = get_database_url()
    if db_url:
        from psycopg import connect
        from psycopg.rows import dict_row

        return connect(db_url, row_factory=dict_row, prepare_threshold=None)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def init_database() -> None:
    with get_connection() as connection:
        if is_postgres():
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS song_requests (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    song_title TEXT NOT NULL,
                    artist_name TEXT NOT NULL,
                    album_name TEXT,
                    spotify_track_id TEXT,
                    album_image_url TEXT,
                    requested_at TIMESTAMPTZ NOT NULL,
                    status TEXT NOT NULL CHECK(status IN ('pending', 'completed', 'rejected')),
                    completed_at TIMESTAMPTZ,
                    rejected_at TIMESTAMPTZ,
                    rejection_reason TEXT,
                    user_device_id TEXT NOT NULL,
                    user_ip_hash TEXT,
                    request_date DATE NOT NULL
                )
                """
            )
        else:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS song_requests (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    song_title TEXT NOT NULL,
                    artist_name TEXT NOT NULL,
                    album_name TEXT,
                    spotify_track_id TEXT,
                    album_image_url TEXT,
                    requested_at TEXT NOT NULL,
                    status TEXT NOT NULL CHECK(status IN ('pending', 'completed', 'rejected')),
                    completed_at TEXT,
                    rejected_at TEXT,
                    rejection_reason TEXT,
                    user_device_id TEXT NOT NULL,
                    user_ip_hash TEXT,
                    request_date TEXT NOT NULL
                )
                """
            )
        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_song_requests_queue
            ON song_requests(status, requested_at)
            """
        )
        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_song_requests_limit
            ON song_requests(user_device_id, request_date)
            """
        )
